name: Workflow Filters and Activites

on:
  workflow_dispatch:
#   schedule:
#     - cron: "*/59 * * * *"
  
  push:
    branches:
      - main
      - '!feature/*'      # ignore pushing to any branch name start with feature using !

  # branch-ignore:
  #   - feature/*       # feature/add-music, feature/updateImages
  #   - test/**         # test/ui/index, test/checkout/payment

  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md       # workflow will only run when a pull request that includes a change on any file other than README.md
    branches:
      - main            # configures your workflow to only run on pull request

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow/job/step is executed for event type - ${{ github.event_name }}"